#!/usr/bin/env ruby
require "rexml/document"
include REXML
service_document = Document.new `tools/scripts/data-deposit-api/test-service-document`
collection = XPath.first(service_document, "//collection/@href")

feed_of_studies = Document.new `tools/scripts/data-deposit-api/test-collection-get #{collection}`
first_study = XPath.first(feed_of_studies, "//entry")
id = first_study.elements["id"].text
study_edit_uri = first_study.attributes["xml:base"]

entry = Document.new `tools/scripts/data-deposit-api/test-edit-get #{study_edit_uri}`
study_edit_media_uri = XPath.first(entry,"//link[@rel='edit-media']").attributes["href"]
statement_uri        = XPath.first(entry,"//link[@rel='http://purl.org/net/sword/terms/statement']").attributes["href"]

zip_of_files_to_add = "example.zip"
puts "adding #{zip_of_files_to_add} to #{study_edit_media_uri}"
out = Document.new `tools/scripts/data-deposit-api/test-edit-media-post-binary #{zip_of_files_to_add} #{study_edit_media_uri}`
if "http://purl.org/net/sword/error/ErrorBadRequest" == out.root.attributes["href"]
    error_summary = XPath.first(out, "//atom:summary").text
    puts "ERROR: #{error_summary}"
else
    deposit_receipt = out
    persistent_uri = XPath.first(deposit_receipt,"//link[@rel='alternate']").attributes["href"]
    puts "file(s) added to #{persistent_uri} . list them with #{statement_uri}"
end
