#!/usr/bin/env ruby
require "rexml/document"
include REXML
service_document = Document.new `tools/scripts/data-deposit-api/test-service-document`
collection = XPath.first(service_document, "//collection")
deposit_target = collection.attributes["href"]

deposit_receipt = Document.new `tools/scripts/data-deposit-api/test-collection-entry-only #{deposit_target}`
study_data_citation = XPath.first(deposit_receipt, "//bibliographicCitation").text
puts "study created: #{study_data_citation}"
