#!/usr/bin/env python
import re
from subprocess import Popen, PIPE
from xml.etree import ElementTree as ET

service_document = ET.fromstring(Popen("tools/scripts/data-deposit-api/test-service-document", stdout=PIPE).communicate()[0])

deposit_target = service_document[0][1].attrib["href"]

print "creating a study using", deposit_target
deposit_receipt_xml = Popen(["tools/scripts/data-deposit-api/test-collection-entry-only", deposit_target], stdout=PIPE).communicate()[0]
deposit_receipt_parsed = ET.fromstring(deposit_receipt_xml)

for link in deposit_receipt_parsed.findall("./{http://www.w3.org/2005/Atom}link"):
    if "edit-media" == link.attrib["rel"]:
        edit_media_uri = link.attrib["href"]
    if "edit" == link.attrib["rel"]:
        edit_uri = link.attrib["href"]

for description in deposit_receipt_parsed.findall("./{http://purl.org/dc/terms/}bibliographicCitation"):
    data_citation = description.text

print "data citation of study created:", data_citation 

zipfile="example.zip"
print "uploading", zipfile, "to", edit_media_uri
out = Popen(["tools/scripts/data-deposit-api/test-edit-media-put-binary", zipfile, edit_media_uri], stdout=PIPE).communicate()[0]
match = re.search("HTTP/1.1 204 No Content", out)
if match:
    print "binary was successfully uploaded"
else:
    print "unable to upload binary to study, output was:"
    print out

print "listing studies..."
feed_of_studies = Popen(["tools/scripts/data-deposit-api/list-studies", deposit_target], stdout=PIPE).communicate()[0]
print feed_of_studies,

#sword_error = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-error"], stdout=PIPE).communicate()[0]);
error_xml = Popen(["tools/scripts/data-deposit-api/test-error"], stdout=PIPE).communicate()[0]
sword_error = ET.fromstring(error_xml)
#for error in sword_error:
#    print "error:", error
#    if "{http://www.w3.org/2005/Atom}summary" == error.tag:
#        error_summary = error.text

#match = re.search("could not extract global ID", error_summary)
match = re.search("Unable to determine target type from url", error_xml)
if match:
    print "global id test succeeded"
else:
    print "error was not thrown"

print "getting entry from", edit_uri
statement = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-edit-get", edit_uri], stdout=PIPE).communicate()[0]);
for line in statement:
    if "{http://purl.org/dc/terms/}bibliographicCitation" == line.tag:
        print "citation from edit-uri:", line.text
    if "{http://www.w3.org/2005/Atom}link" == line.tag:
        if "http://purl.org/net/sword/terms/statement" == line.attrib["rel"]:
            statement_uri = line.attrib["href"]

print "getting statement from", statement_uri
statement = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-statement", statement_uri], stdout=PIPE).communicate()[0]);
for line in statement:
    if "{http://www.w3.org/2005/Atom}title" == line.tag:
        print "title of study created:", line.text
