#!/usr/bin/env ruby
require "rexml/document"
include REXML
service_document = Document.new `tools/scripts/data-deposit-api/test-service-document`
collection = XPath.first(service_document, "//collection/@href")

feed_of_studies = Document.new `tools/scripts/data-deposit-api/test-collection-get #{collection}`
first_study = XPath.first(feed_of_studies, "//entry")
id = first_study.elements["id"].text
study_edit_uri = first_study.attributes["xml:base"]

entry = Document.new `tools/scripts/data-deposit-api/test-edit-get #{study_edit_uri}`
statement_uri = XPath.first(entry,"//link[@rel='http://purl.org/net/sword/terms/statement']").attributes["href"]
data_citation = XPath.first(entry, "//bibliographicCitation").text

statement = Document.new `tools/scripts/data-deposit-api/test-statement #{statement_uri}`
title = statement.root.elements["title"].text
release_state_term = "isReleased"
release_state = XPath.first(statement, "//category[@term='#{release_state_term}']")
draft_state_term = "isInDraft"
draft_state = XPath.first(statement, "//category[@term='#{draft_state_term}']").text
puts "#{release_state_term}:#{release_state.text} #{draft_state_term}:#{draft_state} for #{data_citation}. Files (if any):"
XPath.each( statement, "//entry" ) { |entry|
    url     = entry.elements["content"].attributes["src"]
    type    = entry.elements["content"].attributes["type"]
    updated = entry.elements["updated"]
    puts "- #{url}"
    puts "  - #{updated.text} #{type}"
}
exit
puts "TODO: GET swordv2/edit-media/#{id}.atom (list files)"
puts "TODO: GET swordv2/statement/#{id}.atom (list files)"
puts "TODO: GET swordv2/statement/#{id}.rdf (list files and show state)"
puts "TODO: GET swordv2/edit-media/#{id} (download zip)"
