#!/usr/bin/env ruby
require "rexml/document"
include REXML
service_document = Document.new `tools/scripts/data-deposit-api/test-service-document`
collection = XPath.first(service_document, "//collection/@href")

feed_of_studies = Document.new `tools/scripts/data-deposit-api/test-collection-get #{collection}`
first_study = XPath.first(feed_of_studies, "//entry")
id = first_study.elements["id"].text
study_edit_uri = first_study.attributes["xml:base"]

entry = Document.new `tools/scripts/data-deposit-api/test-edit-get #{study_edit_uri}`
statement_uri = XPath.first(entry,"//link[@rel='http://purl.org/net/sword/terms/statement']").attributes["href"]
edit_media_uri = XPath.first(entry,"//link[@rel='edit-media']").attributes["href"]
data_citation = XPath.first(entry, "//bibliographicCitation").text

replacement_data = "50by1000.dta.zip"
puts "using #{replacement_data} to replace data at #{edit_media_uri}"
out = `tools/scripts/data-deposit-api/test-edit-media-put-binary #{replacement_data} #{edit_media_uri}`
if out.match(/204 No Content/)
    puts "successful replace"
else
    puts "replace failed"
    puts out
end
