#!/usr/bin/env python
import re
from subprocess import Popen, PIPE
from xml.etree import ElementTree as ET

service_document = ET.fromstring(Popen("tools/scripts/data-deposit-api/test-service-document", stdout=PIPE).communicate()[0])

deposit_target = service_document[0][1].attrib["href"]

feed_of_studies = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-collection-get", deposit_target], stdout=PIPE).communicate()[0])

#print "listing all studies..."
all_studies = Popen(["tools/scripts/data-deposit-api/list-studies", deposit_target], stdout=PIPE).communicate()[0]
#print all_studies,
print "finding a study to edit..."
for line in all_studies.splitlines():
    if line.startswith("-"):
        parts = line.split("- ")
        url_only = parts[1]
        pieces = url_only.split("/")
        url_end = pieces[9:11]

url_start = "https://sword:sword@localhost:8181/dvn/api/data-deposit/v1/swordv2/"
statement_uri = url_start + "statement/"       + "/".join(url_end)
edit_uri      = url_start + "edit/" + "/".join(url_end)

print "finding old title from", statement_uri
statement = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-statement", statement_uri], stdout=PIPE).communicate()[0])
for line in statement:
    if "{http://www.w3.org/2005/Atom}title" == line.tag:
        old_title = line.text
    if "{http://www.w3.org/2005/Atom}author" == line.tag:
        for author_line in line:
            old_author = author_line.text

print "replacing title using", edit_uri
deposit_receipt = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-edit-put-atom-entry", edit_uri], stdout=PIPE).communicate()[0])

for line in deposit_receipt:
    if "{http://purl.org/net/sword/terms/}verboseDescription" == line.tag:
        pieces = line.text.split(": ")
        potential_error = pieces[0]
        if "org.swordapp.server.SwordError" == potential_error:
                for line2 in deposit_receipt:
                    if "{http://www.w3.org/2005/Atom}summary" == line2.tag:
                        print line2.text
        else:
            new_title = pieces[1]
            print 'title changed from "', old_title, '" to "', new_title, '"'
            print "dumping XML statement from", statement_uri
            statement = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-statement", statement_uri], stdout=PIPE).communicate()[0])
            for line in statement:
                if "{http://www.w3.org/2005/Atom}author" == line.tag:
                    for author_line in line:
                        new_author = author_line.text

            print 'author changed from "', old_author, '" to "', new_author, '"'
