#!/usr/bin/env ruby
require "rexml/document"
include REXML
service_document = Document.new `tools/scripts/data-deposit-api/test-service-document`
collection = XPath.first(service_document, "//collection/@href")

feed_of_studies = Document.new `tools/scripts/data-deposit-api/test-collection-get #{collection}`
first_study = XPath.first(feed_of_studies, "//entry")
id = first_study.elements["id"].text
study_edit_uri = first_study.attributes["xml:base"]

entry = Document.new `tools/scripts/data-deposit-api/test-edit-get #{study_edit_uri}`
statement_uri = XPath.first(entry,"//link[@rel='http://purl.org/net/sword/terms/statement']").attributes["href"]
edit_media_uri = XPath.first(entry,"//link[@rel='edit-media']").attributes["href"]
data_citation = XPath.first(entry, "//bibliographicCitation").text

statement_old = Document.new `tools/scripts/data-deposit-api/test-statement #{statement_uri}`
old_title = XPath.first(statement_old, "//title").text
old_author = XPath.first(statement_old, "//author/name").text

out = `tools/scripts/data-deposit-api/test-edit-put-atom-entry #{study_edit_uri}`
if out.match(/sword:error/)
    #puts "sword error"
    #puts out
    xml = Document.new out
    error_summary = XPath.first(xml, "//atom:summary").text
    puts "Problem replacing cataloging info: #{error_summary}"
else
    statement_new = Document.new `tools/scripts/data-deposit-api/test-statement #{statement_uri}`
    new_title = XPath.first(statement_new, "//title").text
    new_author = XPath.first(statement_new, "//author/name").text
    puts "title changed from '#{old_title}' to '#{new_title}'"
    puts "author changed from '#{old_author}' to '#{new_author}'"
end
