#!/usr/bin/env python
import re
from subprocess import Popen, PIPE
from xml.etree import ElementTree as ET

service_document = ET.fromstring(Popen("tools/scripts/data-deposit-api/test-service-document", stdout=PIPE).communicate()[0])

deposit_target = service_document[0][1].attrib["href"]

feed_of_studies = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-collection-get", deposit_target], stdout=PIPE).communicate()[0]);

print "listing all studies..."
all_studies = Popen(["tools/scripts/data-deposit-api/list-studies", deposit_target], stdout=PIPE).communicate()[0]
print all_studies,
print "finding a study to edit..."
for line in all_studies.splitlines():
    if line.startswith("-"):
        parts = line.split("- ")
        url_only = parts[1]
        pieces = url_only.split("/")
        url_end = pieces[8:10]

url_start = "https://sword:sword@localhost:8181/dvn/api/data-deposit/swordv2/"
edit_uri =       url_start + "edit/"       + "/".join(url_end)
edit_media_uri = url_start + "edit-media/" + "/".join(url_end)

print "getting statement for", edit_uri
statement = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-statement", edit_uri], stdout=PIPE).communicate()[0]);
for line in statement:
    if "{http://www.w3.org/2005/Atom}title" == line.tag:
        print "title of study to edit:", line.text

replacement_data = "50by1000.dta.zip"
print "replacing data at", edit_media_uri, "with", replacement_data
out = Popen(["tools/scripts/data-deposit-api/test-edit-media-put-binary", replacement_data, edit_media_uri], stdout=PIPE).communicate()[0]
match = re.search("HTTP/1.1 204 No Content", out)
if match:
    print "data replacement was successful"
else:
    print "unable to replace data, output was:"
    print out
