#!/usr/bin/env python
import re
from subprocess import Popen, PIPE
from xml.etree import ElementTree as ET

service_document = ET.fromstring(Popen("tools/scripts/data-deposit-api/test-service-document", stdout=PIPE).communicate()[0])

#deposit_target = service_document[0][1].attrib["href"] # shorter but brittle
deposit_target = service_document.find(".//{http://www.w3.org/2007/app}workspace/{http://www.w3.org/2007/app}collection").attrib["href"]

xml = Popen(["tools/scripts/data-deposit-api/test-collection-get", deposit_target], stdout=PIPE).communicate()[0]
#print xml
#feed_of_studies = ET.fromstring(Popen(["tools/scripts/data-deposit-api/test-collection-get", deposit_target], stdout=PIPE).communicate()[0]);
feed_of_studies = ET.fromstring(xml)

for line in feed_of_studies:
    if "{http://www.w3.org/2005/Atom}entry" == line.tag:
        print "-", line.attrib["{http://www.w3.org/XML/1998/namespace}base"]

# another way...
#print "---"
#for entry in feed_of_studies.findall("./{http://www.w3.org/2005/Atom}entry/"):
#    if not entry.attrib:
#        print "- globalId:", entry.text
#        study_to_edit = entry.text
#    if "{http://www.w3.org/2005/Atom}link" == entry.tag:
#        print "  - file:", entry.attrib["href"]
