#!/usr/bin/env python
import re
from subprocess import Popen, PIPE
from xml.etree import ElementTree as ET

service_document = ET.fromstring(Popen("tools/scripts/data-deposit-api/test-service-document", stdout=PIPE).communicate()[0])
for line1 in service_document:
    if "{http://www.w3.org/2007/app}workspace" == line1.tag:
        for line2 in line1:
            try:
                href = line2.attrib["href"]
                print "href was", href
                parts = href.split("/")
                target = "/".join(parts[9:11])
            except:
                pass

url_start = "https://sword:sword@localhost:8181/dvn/api/data-deposit/v1/swordv2/edit/" + target

deposit_target = url_start

out = Popen(["tools/scripts/data-deposit-api/test-edit-put-in-progress", deposit_target], stdout=PIPE).communicate()[0]
print out
print "deposit target was", deposit_target
