#!/usr/bin/env python
from xml.etree import ElementTree as ET
tree = ET.parse("atom-entry-study.xml")
root = tree.getroot()

for child in root:
    print child.tag, child.text

for child in root.findall("{http://purl.org/dc/terms/}creator"):
    print child.tag, child.text

# might work in Python 3.2: http://stackoverflow.com/questions/10333454/read-xml-file-which-has-xmlns-in-tag-with-python#comment13326297_10338267
#ET.register_namespace("atom", "http://www.w3.org/2005/Atom")
#ET.register_namespace("dcterms", "http://purl.org/dc/terms/")
#for child in root.find("dcterms:creator"):
#    print child.tag, child.text

namespaces1 = {"dcterms": "http://purl.org/dc/terms/"}
for child in root.findall("dcterms:creator", namespaces=namespaces1):
    print child.tag, child.text

namespaces2 = {"dcterms": "http://purl.org/dc/terms/"}
for child in root.findall("{0}dcterms:creator".format(namespaces2)):
    print child.tag, child.text
