#!/bin/sh
if [ "" = "$1" ]; then
  echo >&2 "Please supply a global ID of a study (i.e. hdl:1902.1/12345)"
  exit 1
else
  GLOBAL_ID="/$1"
fi
# --upload-file does a PUT
# No deposit receipt is expected, so use --include to see the return code,
# which can be compared with compare to http://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html#protocoloperations_editingcontent
curl --include --insecure -s --upload-file example.zip -H "Content-Disposition: filename=example.zip" -H "Content-Type: application/zip" https://sword:sword@localhost:8181/dvn/api/data-deposit/swordv2/edit-media$GLOBAL_ID
