#!/bin/sh
if [ "" = "$1" ]; then
  echo >&2 "Please supply the edit-media URI of a study"
  exit 1
else
  EDIT_MEDIA_URI="$1"
fi
# --upload-file does a PUT
# No deposit receipt is expected, so use --include to see the return code,
# which can be compared with compare to http://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html#protocoloperations_editingcontent
curl --include --insecure -s --upload-file example.zip -H "Content-Disposition: filename=example.zip" -H "Content-Type: application/zip" -u sword:sword $EDIT_MEDIA_URI
