#!/bin/sh
if [ "" = "$1" ]; then
  echo >&2 "Please supply a filename of a zip file"
  exit 1
  if [ "" = "$2" ]; then
    echo >&2 "Please supply the edit URI of a study"
    exit 2
  fi
else
  FILENAME="$1"
  EDIT_URI="$2"
fi
curl --insecure -s --data-binary "@$FILENAME" -H "Content-Disposition: filename=$FILENAME"  -H "Content-Type: application/zip" -H "Packaging: http://purl.org/net/sword/package/SimpleZip" -u sword:sword $EDIT_URI
