#!/bin/sh
if [ "" = "$1" ]; then
  echo >&2 "Please supply a collection URI"
  exit 1
else
  COLLECTION_URI="$1"
fi
curl --insecure -s --upload-file "atom-entry-study2.xml" -H "Content-Type: application/atom+xml" -u sword:sword $1 \
| xmllint --format -
