//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.02 at 11:29:17 PM EST 
//


package edu.harvard.iq.dvn.ingest.dsb.zelig;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.harvard.iq.dvn.ingest.dsb.zelig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.harvard.iq.dvn.ingest.dsb.zelig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula }
     * 
     */
    public Zelig.Model.Formula createZeligModelFormula() {
        return new Zelig.Model.Formula();
    }

    /**
     * Create an instance of {@link Zelig.Model.Setx }
     * 
     */
    public Zelig.Model.Setx createZeligModelSetx() {
        return new Zelig.Model.Setx();
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula.Equation.Outcome.ModelingType }
     * 
     */
    public Zelig.Model.Formula.Equation.Outcome.ModelingType createZeligModelFormulaEquationOutcomeModelingType() {
        return new Zelig.Model.Formula.Equation.Outcome.ModelingType();
    }

    /**
     * Create an instance of {@link Zelig }
     * 
     */
    public Zelig createZelig() {
        return new Zelig();
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula.Equation.Explanatory }
     * 
     */
    public Zelig.Model.Formula.Equation.Explanatory createZeligModelFormulaEquationExplanatory() {
        return new Zelig.Model.Formula.Equation.Explanatory();
    }

    /**
     * Create an instance of {@link Zelig.Model }
     * 
     */
    public Zelig.Model createZeligModel() {
        return new Zelig.Model();
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula.Equation.Explanatory.ModelingType }
     * 
     */
    public Zelig.Model.Formula.Equation.Explanatory.ModelingType createZeligModelFormulaEquationExplanatoryModelingType() {
        return new Zelig.Model.Formula.Equation.Explanatory.ModelingType();
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula.Equation.Outcome }
     * 
     */
    public Zelig.Model.Formula.Equation.Outcome createZeligModelFormulaEquationOutcome() {
        return new Zelig.Model.Formula.Equation.Outcome();
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula.Equation }
     * 
     */
    public Zelig.Model.Formula.Equation createZeligModelFormulaEquation() {
        return new Zelig.Model.Formula.Equation();
    }

    /**
     * Create an instance of {@link Zelig.Model.PackageDependency }
     * 
     */
    public Zelig.Model.PackageDependency createZeligModelPackageDependency() {
        return new Zelig.Model.PackageDependency();
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula.Equation.Explanatory.DataType }
     * 
     */
    public Zelig.Model.Formula.Equation.Explanatory.DataType createZeligModelFormulaEquationExplanatoryDataType() {
        return new Zelig.Model.Formula.Equation.Explanatory.DataType();
    }

    /**
     * Create an instance of {@link Zelig.Model.Formula.Equation.Outcome.DataType }
     * 
     */
    public Zelig.Model.Formula.Equation.Outcome.DataType createZeligModelFormulaEquationOutcomeDataType() {
        return new Zelig.Model.Formula.Equation.Outcome.DataType();
    }

    /**
     * Create an instance of {@link Zelig.Model.HelpLink }
     * 
     */
    public Zelig.Model.HelpLink createZeligModelHelpLink() {
        return new Zelig.Model.HelpLink();
    }

}
