//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.02 at 11:29:17 PM EST 
//


package edu.harvard.iq.dvn.ingest.dsb.zelig;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for PACK_REL.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PACK_REL">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="required"/>
 *     &lt;enumeration value="suggested"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum PACKREL {

    @XmlEnumValue("required")
    REQUIRED("required"),
    @XmlEnumValue("suggested")
    SUGGESTED("suggested");
    private final String value;

    PACKREL(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PACKREL fromValue(String v) {
        for (PACKREL c: PACKREL.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
