//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.02 at 11:29:17 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gking.harvard.edu/zelig", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.harvard.iq.dvn.ingest.dsb.zelig;
